// Code generated by protoc-gen-go. DO NOT EDIT.
// source: key.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Key_Format int32

const (
	Key_x509 Key_Format = 0
)

var Key_Format_name = map[int32]string{
	0: "x509",
}

var Key_Format_value = map[string]int32{
	"x509": 0,
}

func (x Key_Format) String() string {
	return proto.EnumName(Key_Format_name, int32(x))
}

func (Key_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2accf5df6005b7d4, []int{0, 0}
}

type Key struct {
	Format               Key_Format `protobuf:"varint,1,opt,name=format,proto3,enum=protos.Key_Format" json:"format,omitempty"`
	Data                 []byte     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_2accf5df6005b7d4, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetFormat() Key_Format {
	if m != nil {
		return m.Format
	}
	return Key_x509
}

func (m *Key) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.Key_Format", Key_Format_name, Key_Format_value)
	proto.RegisterType((*Key)(nil), "protos.Key")
}

func init() { proto.RegisterFile("key.proto", fileDescriptor_2accf5df6005b7d4) }

var fileDescriptor_2accf5df6005b7d4 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4e, 0xad, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x91, 0x5c, 0xcc, 0xde, 0xa9,
	0x95, 0x42, 0x5a, 0x5c, 0x6c, 0x69, 0xf9, 0x45, 0xb9, 0x89, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x7c, 0x46, 0x42, 0x10, 0x65, 0xc5, 0x7a, 0xde, 0xa9, 0x95, 0x7a, 0x6e, 0x60, 0x99, 0x20, 0xa8,
	0x0a, 0x21, 0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20,
	0x30, 0x5b, 0x49, 0x88, 0x8b, 0x0d, 0xa2, 0x4a, 0x88, 0x83, 0x8b, 0xa5, 0xc2, 0xd4, 0xc0, 0x52,
	0x80, 0x21, 0x09, 0x62, 0x85, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x57, 0xab, 0x1a, 0x2c, 0x76,
	0x00, 0x00, 0x00,
}
