// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package crabfs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DHTNameRecordV1 struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Perm                 uint32   `protobuf:"varint,3,opt,name=perm,proto3" json:"perm,omitempty"`
	Length               int64    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Mtime                string   `protobuf:"bytes,5,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Signature            []byte   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DHTNameRecordV1) Reset()         { *m = DHTNameRecordV1{} }
func (m *DHTNameRecordV1) String() string { return proto.CompactTextString(m) }
func (*DHTNameRecordV1) ProtoMessage()    {}
func (*DHTNameRecordV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *DHTNameRecordV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHTNameRecordV1.Unmarshal(m, b)
}
func (m *DHTNameRecordV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHTNameRecordV1.Marshal(b, m, deterministic)
}
func (m *DHTNameRecordV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHTNameRecordV1.Merge(m, src)
}
func (m *DHTNameRecordV1) XXX_Size() int {
	return xxx_messageInfo_DHTNameRecordV1.Size(m)
}
func (m *DHTNameRecordV1) XXX_DiscardUnknown() {
	xxx_messageInfo_DHTNameRecordV1.DiscardUnknown(m)
}

var xxx_messageInfo_DHTNameRecordV1 proto.InternalMessageInfo

func (m *DHTNameRecordV1) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DHTNameRecordV1) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DHTNameRecordV1) GetPerm() uint32 {
	if m != nil {
		return m.Perm
	}
	return 0
}

func (m *DHTNameRecordV1) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *DHTNameRecordV1) GetMtime() string {
	if m != nil {
		return m.Mtime
	}
	return ""
}

func (m *DHTNameRecordV1) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ProtocolRequest struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Cid                  []byte   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length               int64    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	PathName             string   `protobuf:"bytes,5,opt,name=pathName,proto3" json:"pathName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtocolRequest) Reset()         { *m = ProtocolRequest{} }
func (m *ProtocolRequest) String() string { return proto.CompactTextString(m) }
func (*ProtocolRequest) ProtoMessage()    {}
func (*ProtocolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *ProtocolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolRequest.Unmarshal(m, b)
}
func (m *ProtocolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolRequest.Marshal(b, m, deterministic)
}
func (m *ProtocolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolRequest.Merge(m, src)
}
func (m *ProtocolRequest) XXX_Size() int {
	return xxx_messageInfo_ProtocolRequest.Size(m)
}
func (m *ProtocolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolRequest proto.InternalMessageInfo

func (m *ProtocolRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ProtocolRequest) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *ProtocolRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ProtocolRequest) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ProtocolRequest) GetPathName() string {
	if m != nil {
		return m.PathName
	}
	return ""
}

func init() {
	proto.RegisterType((*DHTNameRecordV1)(nil), "crabfs.DHTNameRecordV1")
	proto.RegisterType((*ProtocolRequest)(nil), "crabfs.ProtocolRequest")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x89, 0xdb, 0x06, 0x3b, 0x54, 0x2a, 0x41, 0x24, 0x88, 0x87, 0xd0, 0x53, 0x4e, 0x82,
	0xf8, 0x0a, 0x1e, 0x3c, 0x89, 0x04, 0xf1, 0x9e, 0x66, 0x67, 0xdb, 0x85, 0x66, 0x13, 0x93, 0xe9,
	0x63, 0xf8, 0x14, 0xbe, 0xa8, 0x24, 0x06, 0xf7, 0x24, 0xbd, 0xfd, 0xdf, 0x7f, 0xf8, 0xe7, 0x63,
	0x60, 0xed, 0x82, 0xf7, 0x61, 0x7a, 0x88, 0x29, 0x50, 0x10, 0xdc, 0x25, 0xbb, 0x1b, 0xf2, 0xf6,
	0x9b, 0xc1, 0xe6, 0xf9, 0xe5, 0xfd, 0xd5, 0x7a, 0x34, 0xe8, 0x42, 0xea, 0x3f, 0x1e, 0xc5, 0x3d,
	0xac, 0x68, 0xf4, 0x98, 0xc9, 0xfa, 0x28, 0x99, 0x62, 0x7a, 0x65, 0xe6, 0x42, 0x08, 0x58, 0xf4,
	0x96, 0xac, 0xbc, 0x50, 0x4c, 0xaf, 0x4d, 0xcd, 0xa5, 0x8b, 0x98, 0xbc, 0xec, 0x14, 0xd3, 0x57,
	0xa6, 0x66, 0x71, 0x0b, 0xfc, 0x88, 0xd3, 0x9e, 0x0e, 0x72, 0xa1, 0x98, 0xee, 0x4c, 0x23, 0x71,
	0x03, 0x4b, 0x5f, 0xd6, 0xe4, 0xb2, 0x2e, 0xff, 0x42, 0xb9, 0x99, 0xc7, 0xfd, 0x64, 0xe9, 0x94,
	0x50, 0xf2, 0x3a, 0x3d, 0x17, 0xdb, 0x2f, 0x06, 0x9b, 0xb7, 0xe2, 0xed, 0xc2, 0xd1, 0xe0, 0xe7,
	0x09, 0x33, 0x9d, 0xb1, 0xbc, 0x86, 0xce, 0x8d, 0x7d, 0x93, 0x2c, 0xb1, 0xf8, 0x84, 0x61, 0xc8,
	0x48, 0xd5, 0xb2, 0x33, 0x8d, 0xfe, 0xf5, 0xbc, 0x83, 0xcb, 0x68, 0xe9, 0x50, 0x3e, 0xd3, 0x54,
	0xff, 0x78, 0xc7, 0xeb, 0x13, 0x9f, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xee, 0x08, 0x9b,
	0x54, 0x01, 0x00, 0x00,
}
