// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package crabfs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DHTNameRecord struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ContentID            []byte   `protobuf:"bytes,2,opt,name=contentID,proto3" json:"contentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DHTNameRecord) Reset()         { *m = DHTNameRecord{} }
func (m *DHTNameRecord) String() string { return proto.CompactTextString(m) }
func (*DHTNameRecord) ProtoMessage()    {}
func (*DHTNameRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *DHTNameRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHTNameRecord.Unmarshal(m, b)
}
func (m *DHTNameRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHTNameRecord.Marshal(b, m, deterministic)
}
func (m *DHTNameRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHTNameRecord.Merge(m, src)
}
func (m *DHTNameRecord) XXX_Size() int {
	return xxx_messageInfo_DHTNameRecord.Size(m)
}
func (m *DHTNameRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DHTNameRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DHTNameRecord proto.InternalMessageInfo

func (m *DHTNameRecord) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DHTNameRecord) GetContentID() []byte {
	if m != nil {
		return m.ContentID
	}
	return nil
}

func init() {
	proto.RegisterType((*DHTNameRecord)(nil), "crabfs.DHTNameRecord")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x2e, 0x4a, 0x4c, 0x4a, 0x2b,
	0x56, 0xf2, 0xe6, 0xe2, 0x75, 0xf1, 0x08, 0xf1, 0x4b, 0xcc, 0x4d, 0x0d, 0x4a, 0x4d, 0xce, 0x2f,
	0x4a, 0x11, 0x92, 0xe1, 0xe2, 0x2c, 0xc9, 0xcc, 0x4d, 0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0x90, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08, 0x80, 0x64, 0x93, 0xf3, 0xf3, 0x4a, 0x52, 0xf3, 0x4a,
	0x3c, 0x5d, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0x10, 0x02, 0x49, 0x6c, 0x60, 0xb3, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x45, 0xec, 0xcd, 0x1d, 0x6b, 0x00, 0x00, 0x00,
}
