// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DHTNameRecord struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Delete               bool     `protobuf:"varint,4,opt,name=delete,proto3" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DHTNameRecord) Reset()         { *m = DHTNameRecord{} }
func (m *DHTNameRecord) String() string { return proto.CompactTextString(m) }
func (*DHTNameRecord) ProtoMessage()    {}
func (*DHTNameRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *DHTNameRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHTNameRecord.Unmarshal(m, b)
}
func (m *DHTNameRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHTNameRecord.Marshal(b, m, deterministic)
}
func (m *DHTNameRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHTNameRecord.Merge(m, src)
}
func (m *DHTNameRecord) XXX_Size() int {
	return xxx_messageInfo_DHTNameRecord.Size(m)
}
func (m *DHTNameRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DHTNameRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DHTNameRecord proto.InternalMessageInfo

func (m *DHTNameRecord) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DHTNameRecord) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DHTNameRecord) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *DHTNameRecord) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

type BlockMetadata struct {
	Cid                  []byte   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	PaddingStart         int64    `protobuf:"varint,4,opt,name=paddingStart,proto3" json:"paddingStart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMetadata) Reset()         { *m = BlockMetadata{} }
func (m *BlockMetadata) String() string { return proto.CompactTextString(m) }
func (*BlockMetadata) ProtoMessage()    {}
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *BlockMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetadata.Unmarshal(m, b)
}
func (m *BlockMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetadata.Marshal(b, m, deterministic)
}
func (m *BlockMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetadata.Merge(m, src)
}
func (m *BlockMetadata) XXX_Size() int {
	return xxx_messageInfo_BlockMetadata.Size(m)
}
func (m *BlockMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetadata proto.InternalMessageInfo

func (m *BlockMetadata) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *BlockMetadata) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *BlockMetadata) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BlockMetadata) GetPaddingStart() int64 {
	if m != nil {
		return m.PaddingStart
	}
	return 0
}

type CrabObject struct {
	Blocks               map[int64]*BlockMetadata `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Mtime                string                   `protobuf:"bytes,2,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Size                 int64                    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Key                  []byte                   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CrabObject) Reset()         { *m = CrabObject{} }
func (m *CrabObject) String() string { return proto.CompactTextString(m) }
func (*CrabObject) ProtoMessage()    {}
func (*CrabObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *CrabObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrabObject.Unmarshal(m, b)
}
func (m *CrabObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrabObject.Marshal(b, m, deterministic)
}
func (m *CrabObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrabObject.Merge(m, src)
}
func (m *CrabObject) XXX_Size() int {
	return xxx_messageInfo_CrabObject.Size(m)
}
func (m *CrabObject) XXX_DiscardUnknown() {
	xxx_messageInfo_CrabObject.DiscardUnknown(m)
}

var xxx_messageInfo_CrabObject proto.InternalMessageInfo

func (m *CrabObject) GetBlocks() map[int64]*BlockMetadata {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *CrabObject) GetMtime() string {
	if m != nil {
		return m.Mtime
	}
	return ""
}

func (m *CrabObject) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CrabObject) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type BlockStreamRequest struct {
	Cid                  []byte   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockStreamRequest) Reset()         { *m = BlockStreamRequest{} }
func (m *BlockStreamRequest) String() string { return proto.CompactTextString(m) }
func (*BlockStreamRequest) ProtoMessage()    {}
func (*BlockStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *BlockStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStreamRequest.Unmarshal(m, b)
}
func (m *BlockStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStreamRequest.Marshal(b, m, deterministic)
}
func (m *BlockStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStreamRequest.Merge(m, src)
}
func (m *BlockStreamRequest) XXX_Size() int {
	return xxx_messageInfo_BlockStreamRequest.Size(m)
}
func (m *BlockStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStreamRequest proto.InternalMessageInfo

func (m *BlockStreamRequest) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func init() {
	proto.RegisterType((*DHTNameRecord)(nil), "protos.DHTNameRecord")
	proto.RegisterType((*BlockMetadata)(nil), "protos.BlockMetadata")
	proto.RegisterType((*CrabObject)(nil), "protos.CrabObject")
	proto.RegisterMapType((map[int64]*BlockMetadata)(nil), "protos.CrabObject.BlocksEntry")
	proto.RegisterType((*BlockStreamRequest)(nil), "protos.BlockStreamRequest")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xdd, 0x4a, 0x33, 0x31,
	0x10, 0x25, 0xdd, 0xb6, 0x7c, 0x9d, 0x6e, 0xa1, 0x84, 0x4f, 0x59, 0x44, 0x64, 0xd9, 0x0b, 0x59,
	0x10, 0x7a, 0x51, 0x41, 0xc4, 0x4b, 0x7f, 0xc0, 0x1b, 0x7f, 0x48, 0x7d, 0x81, 0xec, 0x6e, 0x28,
	0x6b, 0x9b, 0x4d, 0x4d, 0xa6, 0x4a, 0x7d, 0x4c, 0x9f, 0x48, 0x32, 0x69, 0x59, 0x8b, 0x5e, 0xe5,
	0xcc, 0xcc, 0x99, 0x39, 0x87, 0x13, 0x88, 0x4b, 0xa3, 0xb5, 0x69, 0x26, 0x2b, 0x6b, 0xd0, 0xf0,
	0x3e, 0x3d, 0x2e, 0xfb, 0x80, 0xd1, 0xed, 0xfd, 0xcb, 0xa3, 0xd4, 0x4a, 0xa8, 0xd2, 0xd8, 0x8a,
	0x1f, 0xc3, 0x00, 0x6b, 0xad, 0x1c, 0x4a, 0xbd, 0x4a, 0x58, 0xca, 0xf2, 0x81, 0x68, 0x1b, 0x9c,
	0x43, 0xb7, 0x92, 0x28, 0x93, 0x4e, 0xca, 0xf2, 0x58, 0x10, 0xf6, 0x1b, 0xae, 0x9e, 0x37, 0x12,
	0xd7, 0x56, 0x25, 0x11, 0x0d, 0xda, 0x06, 0x3f, 0x84, 0x7e, 0xa5, 0x96, 0x0a, 0x55, 0xd2, 0x4d,
	0x59, 0xfe, 0x4f, 0x6c, 0xab, 0xcc, 0xc0, 0xe8, 0x7a, 0x69, 0xca, 0xc5, 0x83, 0x42, 0x49, 0x67,
	0xc6, 0x10, 0x95, 0x75, 0x45, 0x92, 0xb1, 0xf0, 0x90, 0xff, 0x87, 0x9e, 0x43, 0x69, 0x91, 0xd4,
	0x22, 0x11, 0x0a, 0x6f, 0xc1, 0xd5, 0x9f, 0x41, 0x29, 0x12, 0x84, 0x79, 0x06, 0xf1, 0x4a, 0x56,
	0x55, 0xdd, 0xcc, 0x67, 0xb4, 0xd0, 0xa5, 0xd9, 0x5e, 0x2f, 0xfb, 0x62, 0x00, 0x37, 0x56, 0x16,
	0x4f, 0xc5, 0xab, 0x2a, 0x91, 0x5f, 0x40, 0xbf, 0xf0, 0xfa, 0x2e, 0x61, 0x69, 0x94, 0x0f, 0xa7,
	0x27, 0x21, 0x18, 0x37, 0x69, 0x39, 0x13, 0x32, 0xe8, 0xee, 0x1a, 0xb4, 0x1b, 0xb1, 0x65, 0x7b,
	0x53, 0xda, 0xe7, 0x41, 0xa6, 0x06, 0x22, 0x14, 0x7f, 0x9a, 0x1a, 0x43, 0xb4, 0x50, 0x1b, 0xf2,
	0x12, 0x0b, 0x0f, 0x8f, 0x9e, 0x61, 0xf8, 0xe3, 0xe4, 0x8e, 0xc0, 0x68, 0xc7, 0x43, 0x7e, 0x06,
	0xbd, 0x77, 0xb9, 0x5c, 0x87, 0xe3, 0xc3, 0xe9, 0xc1, 0xce, 0xd3, 0x5e, 0x52, 0x22, 0x70, 0xae,
	0x3a, 0x97, 0x2c, 0x3b, 0x05, 0x4e, 0xb3, 0x19, 0x5a, 0x25, 0xb5, 0x50, 0x6f, 0x6b, 0xe5, 0xf0,
	0x77, 0x94, 0x45, 0xf8, 0xee, 0xf3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0xf8, 0x69, 0x4a,
	0x05, 0x02, 0x00, 0x00,
}
